cpufreq : Impulse :drop cpufreq_put_global_kobject(); function calls
Upstream commit ade389026b4fc7aef2ccd47e4147cc3cabe11215 dropped this funtion to fix uevent broken in cpufreq driver.

so drop this depracated function call which otherwise result in following compilation error

drivers/cpufreq/cpufreq_impulse.c:12:
drivers/cpufreq/cpufreq_impulse.c: In function ‘cpufreq_governor_impulse’:
drivers/cpufreq/cpufreq_impulse.c:1224:12: error:
implicit declaration of function
‘cpufreq_get_global_kobject’; did you mean
‘cpufreq_get_policy’?
[-Werror=implicit-function-declaration]
    WARN_ON(cpufreq_get_global_kobject());
            ^ include/asm-generic/bug.h:86:25: note: in
definition of macro ‘WARN_ON’
  int __ret_warn_on = !!(condition); \
                         ^~~~~~~~~
drivers/cpufreq/cpufreq_impulse.c:1235:5: error: implicit
declaration of function ‘cpufreq_put_global_kobject’; did
you mean ‘cpufreq_get_policy’?
[-Werror=implicit-function-declaration]
     cpufreq_put_global_kobject();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
     cpufreq_get_policy

Signed-off-by: Akianonymus <anonymus.aki@gmail.com>